extends Node

#navigation signals
signal move_to_mining_pane
signal move_to_shop_pane
signal move_to_central_hub_from_mining_page
signal move_to_central_hub_from_shop_pane
signal start_fight

#mining panel signals
signal update_ferrite_count
signal update_ferrite_bars_count
signal update_platinum_count
signal show_upgrade_panel
signal hide_upgrade_panel
signal add_drone
signal add_platinum_drone
